version: "3.8"

services:
  web:
    command:
        bash -c "python manage.py migrate
        && python manage.py runserver 0.0.0.0:8000"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_NAME=parser
      - POSTGRES_USER=parser
      - POSTGRES_PASSWORD=parser
    ports:
      - '8000:8000'
    volumes:
      - ./:/usr/app/src/
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=parser
      - POSTGRES_USER=parser
      - POSTGRES_PASSWORD=parser
    ports:
      - '5432:5432'


  redis:
    image: redis

  celery:
    build:
      context: ./
      dockerfile: Dockerfile
    command: celery -A project worker -l debug
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_NAME=parser
      - POSTGRES_USER=parser
      - POSTGRES_PASSWORD=parser
    volumes:
      - ./:/usr/app/src/

    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_NAME=parser
      - POSTGRES_USER=parser
      - POSTGRES_PASSWORD=parser
    command: celery -A project worker -l debug
    depends_on:
      - redis
      - db
