# Generated by Django 3.2.13 on 2022-05-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(blank=True, null=True, verbose_name='Полное наименование')),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Краткое наименование')),
                ('registry_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код по Сводному реестру')),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
                ('identification_number', models.TextField(blank=True, null=True, verbose_name='ИНН')),
                ('registration_reason_code', models.TextField(blank=True, null=True, verbose_name='КПП')),
                ('state_registration_number', models.TextField(blank=True, null=True, verbose_name='ОГРН')),
                ('classifier_of_municipal_territories', models.TextField(blank=True, null=True, verbose_name='ОКТМО')),
                ('location_address', models.TextField(blank=True, null=True, verbose_name='Место нахождения')),
            ],
        ),
    ]
